// <auto-generated />
using System;
using AttendanceShiftingManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceShiftingManagement.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326171235_AddBudgetManagementSchema")]
    partial class AddBudgetManagementSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AttendanceShiftingManagement.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("details");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AssistanceCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("approved_amount");

                    b.Property<string>("AssistanceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("assistance_type");

                    b.Property<int?>("AyudaProgramId")
                        .HasColumnType("int")
                        .HasColumnName("ayuda_program_id");

                    b.Property<int?>("BudgetLedgerEntryId")
                        .HasColumnType("int")
                        .HasColumnName("budget_ledger_entry_id");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("case_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int")
                        .HasColumnName("household_id");

                    b.Property<int?>("HouseholdMemberId")
                        .HasColumnType("int")
                        .HasColumnName("household_member_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("priority");

                    b.Property<decimal?>("RequestedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("requested_amount");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_on");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<DateTime?>("ScheduledReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduled_release_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AyudaProgramId");

                    b.HasIndex("BudgetLedgerEntryId");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.HasIndex("HouseholdMemberId");

                    b.ToTable("assistance_cases");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AyudaProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("program_code");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("program_name");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("program_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProgramCode")
                        .IsUnique();

                    b.ToTable("ayuda_programs");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BeneficiaryAssistanceLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BeneficiaryId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("CivilRegistryId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("civil_registry_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_date");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("remarks");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source_module");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CivilRegistryId");

                    b.ToTable("beneficiary_assistance_ledger");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BeneficiaryStaging", b =>
                {
                    b.Property<int>("StagingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StagingID"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Age")
                        .HasColumnType("longtext");

                    b.Property<string>("BeneficiaryId")
                        .HasColumnType("longtext");

                    b.Property<string>("CauseOfDisability")
                        .HasColumnType("longtext");

                    b.Property<string>("CivilRegistryId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext");

                    b.Property<string>("DisabilityType")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSenior")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<int?>("LinkedHouseholdId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedHouseholdMemberId")
                        .HasColumnType("int");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("PwdIdNo")
                        .HasColumnType("longtext");

                    b.Property<long?>("ResidentsId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("SeniorIdNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("StagingID");

                    b.HasIndex("CivilRegistryId");

                    b.ToTable("BeneficiaryStaging");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BudgetLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("entry_type");

                    b.Property<string>("FeatureSource")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("feature_source");

                    b.Property<decimal>("GovernmentPortion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("government_portion");

                    b.Property<decimal>("PrivatePortion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("private_portion");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int")
                        .HasColumnName("program_id");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("int")
                        .HasColumnName("recipient_count");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("remarks");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("source_record_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("FeatureSource", "SourceRecordId", "EntryType");

                    b.ToTable("budget_ledger_entries");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("attendance_date");

                    b.Property<string>("OcrExtractedName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ocr_extracted_name");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int")
                        .HasColumnName("participant_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("cash_for_work_attendance");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AyudaProgramId")
                        .HasColumnType("int")
                        .HasColumnName("ayuda_program_id");

                    b.Property<int?>("BudgetLedgerEntryId")
                        .HasColumnType("int")
                        .HasColumnName("budget_ledger_entry_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("event_date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ReleaseAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("release_amount");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("released_at");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AyudaProgramId");

                    b.HasIndex("BudgetLedgerEntryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("cash_for_work_events");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("added_by_user_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("HouseholdMemberId")
                        .HasColumnType("int")
                        .HasColumnName("household_member_id");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("HouseholdMemberId");

                    b.HasIndex("EventId", "HouseholdMemberId")
                        .IsUnique();

                    b.ToTable("cash_for_work_participants");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.GovernmentBudgetSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("office_code");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("office_name");

                    b.Property<string>("SourceRowId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("source_row_id");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("spent_amount");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sync_status");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("YearlyBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("yearly_budget_id");

                    b.HasKey("Id");

                    b.ToTable("government_budget_snapshots");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.GrievanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<int?>("AssistanceCaseId")
                        .HasColumnType("int")
                        .HasColumnName("assistance_case_id");

                    b.Property<string>("BeneficiaryId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("beneficiary_id");

                    b.Property<int?>("CashForWorkEventId")
                        .HasColumnType("int")
                        .HasColumnName("cash_for_work_event_id");

                    b.Property<string>("CivilRegistryId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("civil_registry_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("FiledByUserId")
                        .HasColumnType("int")
                        .HasColumnName("filed_by_user_id");

                    b.Property<string>("GrievanceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("grievance_number");

                    b.Property<string>("ResolutionRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("resolution_remarks");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("StagingId")
                        .HasColumnType("int")
                        .HasColumnName("staging_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GrievanceNumber")
                        .IsUnique();

                    b.ToTable("grievance_records");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address_line");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("head_name");

                    b.Property<string>("HouseholdCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("household_code");

                    b.Property<string>("Purok")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("purok");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdCode")
                        .IsUnique();

                    b.ToTable("households");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.HouseholdMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsCashForWorkEligible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_cash_for_work_eligible");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("RelationshipToHead")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("relationship_to_head");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("household_members");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.PrivateDonation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_received");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("donor_name");

                    b.Property<string>("DonorType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("donor_type");

                    b.Property<string>("ProofFilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("proof_file_path");

                    b.Property<string>("ProofReferenceNumber")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("proof_reference_number");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("proof_type");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("received_by_user_id");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("reference_number");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.ToTable("private_donations");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nickname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.ActivityLog", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AssistanceCase", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "AyudaProgram")
                        .WithMany()
                        .HasForeignKey("AyudaProgramId");

                    b.HasOne("AttendanceShiftingManagement.Models.BudgetLedgerEntry", "BudgetLedgerEntry")
                        .WithMany()
                        .HasForeignKey("BudgetLedgerEntryId");

                    b.HasOne("AttendanceShiftingManagement.Models.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceShiftingManagement.Models.HouseholdMember", "HouseholdMember")
                        .WithMany()
                        .HasForeignKey("HouseholdMemberId");

                    b.Navigation("AyudaProgram");

                    b.Navigation("BudgetLedgerEntry");

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkAttendance", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkParticipant", "Participant")
                        .WithMany("Attendances")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceShiftingManagement.Models.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkEvent", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "AyudaProgram")
                        .WithMany()
                        .HasForeignKey("AyudaProgramId");

                    b.HasOne("AttendanceShiftingManagement.Models.BudgetLedgerEntry", "BudgetLedgerEntry")
                        .WithMany()
                        .HasForeignKey("BudgetLedgerEntryId");

                    b.HasOne("AttendanceShiftingManagement.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AyudaProgram");

                    b.Navigation("BudgetLedgerEntry");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkParticipant", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkEvent", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceShiftingManagement.Models.HouseholdMember", "HouseholdMember")
                        .WithMany("CashForWorkParticipants")
                        .HasForeignKey("HouseholdMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Event");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.HouseholdMember", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.UserProfile", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.User", null)
                        .WithOne()
                        .HasForeignKey("AttendanceShiftingManagement.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkEvent", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkParticipant", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.Household", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.HouseholdMember", b =>
                {
                    b.Navigation("CashForWorkParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
