// <auto-generated />
using System;
using AttendanceShiftingManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceShiftingManagement.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AttendanceShiftingManagement.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("activity_logs");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AssistanceCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("approved_amount");

                    b.Property<int?>("AssistanceCaseBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assistance_case_budget_id");

                    b.Property<string>("AssistanceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("assistance_type");

                    b.Property<int?>("AyudaProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ayuda_program_id");

                    b.Property<int?>("BudgetLedgerEntryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("budget_ledger_entry_id");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("case_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_id");

                    b.Property<int?>("HouseholdMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_member_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("ReleaseKind")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("release_kind");

                    b.Property<decimal?>("RequestedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("requested_amount");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_on");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution_notes");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<DateTime?>("ScheduledReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_release_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidatedBeneficiaryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("validated_beneficiary_id");

                    b.Property<string>("ValidatedBeneficiaryName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("validated_beneficiary_name");

                    b.Property<string>("ValidatedCivilRegistryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("validated_civil_registry_id");

                    b.HasKey("Id");

                    b.HasIndex("AssistanceCaseBudgetId");

                    b.HasIndex("AyudaProgramId");

                    b.HasIndex("BudgetLedgerEntryId");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.HasIndex("HouseholdMemberId");

                    b.ToTable("assistance_cases");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AssistanceCaseBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssistanceType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("assistance_type");

                    b.Property<decimal?>("BudgetCap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("budget_cap");

                    b.Property<string>("BudgetCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_code");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCode")
                        .IsUnique();

                    b.ToTable("assistance_case_budgets");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AyudaProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssistanceType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("assistance_type");

                    b.Property<decimal?>("BudgetCap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("budget_cap");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DistributionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("distribution_status");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("program_code");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("program_name");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("program_type");

                    b.Property<decimal?>("QuantityPerBeneficiary")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity_per_beneficiary");

                    b.Property<string>("ReleaseKind")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("release_kind");

                    b.Property<int?>("SourceDonationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_donation_id");

                    b.Property<int?>("SourceGGMSBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_ggms_budget_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_amount");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProgramCode")
                        .IsUnique();

                    b.HasIndex("SourceDonationId");

                    b.HasIndex("SourceGGMSBudgetId");

                    b.ToTable("ayuda_programs");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AyudaProjectBeneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("added_by_user_id");

                    b.Property<int>("AyudaProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ayuda_program_id");

                    b.Property<string>("BeneficiaryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("beneficiary_id");

                    b.Property<int>("BeneficiaryStagingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beneficiary_staging_id");

                    b.Property<string>("CivilRegistryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("civil_registry_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_id");

                    b.Property<int?>("HouseholdMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_member_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("status_reason");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("status_updated_at");

                    b.Property<int?>("StatusUpdatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_updated_by_user_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AyudaProgramId", "BeneficiaryStagingId")
                        .IsUnique();

                    b.ToTable("ayuda_project_beneficiaries");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AyudaProjectClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssistanceTypeSnapshot")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("assistance_type_snapshot");

                    b.Property<int>("AyudaProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ayuda_program_id");

                    b.Property<string>("BeneficiaryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("beneficiary_id");

                    b.Property<int>("BeneficiaryStagingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beneficiary_staging_id");

                    b.Property<string>("CivilRegistryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("civil_registry_id");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("claimed_at");

                    b.Property<int>("ClaimedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claimed_by_user_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_id");

                    b.Property<int?>("HouseholdMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_member_id");

                    b.Property<string>("ItemDescriptionSnapshot")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_description_snapshot");

                    b.Property<string>("ItemNameSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name_snapshot");

                    b.Property<int?>("ProjectBeneficiaryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_beneficiary_id");

                    b.Property<string>("QrPayload")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("qr_payload");

                    b.Property<decimal?>("QuantitySnapshot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity_snapshot");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitAmountSnapshot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_amount_snapshot");

                    b.Property<string>("UnitOfMeasureSnapshot")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_of_measure_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("AyudaProgramId", "BeneficiaryStagingId")
                        .IsUnique();

                    b.ToTable("ayuda_project_claims");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BarangayAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_on");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_tag");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.ToTable("barangay_assets");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BeneficiaryAssistanceLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BeneficiaryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("CivilRegistryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("civil_registry_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_module");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CivilRegistryId");

                    b.ToTable("beneficiary_assistance_ledger");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BeneficiaryDigitalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BeneficiaryStagingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beneficiary_staging_id");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("card_number");

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_id");

                    b.Property<int?>("HouseholdMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_member_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("issued_at");

                    b.Property<int>("IssuedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued_by_user_id");

                    b.Property<DateTime?>("LastPrintedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_printed_at");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_path");

                    b.Property<string>("QrPayload")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("qr_payload");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryStagingId")
                        .IsUnique();

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("QrPayload")
                        .IsUnique();

                    b.ToTable("beneficiary_digital_ids");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BeneficiaryStaging", b =>
                {
                    b.Property<int>("StagingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeneficiaryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CauseOfDisability")
                        .HasColumnType("TEXT");

                    b.Property<string>("CivilRegistryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabilityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSenior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedHouseholdId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedHouseholdMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PwdIdNo")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResidentsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeniorIdNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("StagingID");

                    b.HasIndex("CivilRegistryId");

                    b.HasIndex("ResidentsId");

                    b.ToTable("BeneficiaryStaging");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BudgetLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AssistanceCaseBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assistance_case_budget_id");

                    b.Property<int?>("CashForWorkBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cash_for_work_budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type");

                    b.Property<string>("FeatureSource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("feature_source");

                    b.Property<decimal>("GovernmentPortion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("government_portion");

                    b.Property<decimal>("PrivatePortion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("private_portion");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("program_id");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recipient_count");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("ReleaseKind")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("release_kind");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssistanceCaseBudgetId");

                    b.HasIndex("CashForWorkBudgetId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("FeatureSource", "SourceRecordId", "EntryType");

                    b.ToTable("budget_ledger_entries");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("attendance_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OcrExtractedName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("ocr_extracted_name");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("participant_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("cash_for_work_attendance");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal?>("BudgetCap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("budget_cap");

                    b.Property<string>("BudgetCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_code");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCode")
                        .IsUnique();

                    b.ToTable("cash_for_work_budgets");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AyudaProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ayuda_program_id");

                    b.Property<string>("BenefitDescription")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("benefit_description");

                    b.Property<string>("BenefitType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("benefit_type");

                    b.Property<int?>("BudgetLedgerEntryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("budget_ledger_entry_id");

                    b.Property<int?>("CashForWorkBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cash_for_work_budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_date");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_kind");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("finish_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ReleaseAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("release_amount");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("released_at");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<decimal>("UnitAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AyudaProgramId");

                    b.HasIndex("BudgetLedgerEntryId");

                    b.HasIndex("CashForWorkBudgetId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("cash_for_work_events");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("added_by_user_id");

                    b.Property<int?>("BeneficiaryStagingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beneficiary_staging_id");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_id");

                    b.Property<int?>("HouseholdMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_member_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("BeneficiaryStagingId");

                    b.HasIndex("HouseholdMemberId");

                    b.HasIndex("EventId", "BeneficiaryStagingId")
                        .IsUnique();

                    b.ToTable("cash_for_work_participants");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.EquipmentBorrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("asset_id");

                    b.Property<string>("BeneficiaryId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("BeneficiaryName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("beneficiary_name");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("borrow_date");

                    b.Property<string>("ConditionIn")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_in");

                    b.Property<string>("ConditionOut")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_out");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("return_date");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("BeneficiaryId");

                    b.ToTable("equipment_borrowings");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.GgmsAllocationCache", b =>
                {
                    b.Property<int>("GgmsAllocationCacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRowId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearlyBudgetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GgmsAllocationCacheId");

                    b.ToTable("ggms_allocation_cache");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.GgmsPendingTransactionCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ggms_pending_transaction_cache");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.GgmsTransactionCache", b =>
                {
                    b.Property<int>("GgmsTransactionCacheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeCode")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("GgmsTransactionCacheId");

                    b.ToTable("ggms_transaction_cache");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.GovernmentBudgetSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocatedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("allocated_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("office_code");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("office_name");

                    b.Property<string>("SourceRowId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_row_id");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("spent_amount");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sync_status");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at");

                    b.Property<int?>("TargetAssistanceCaseBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_assistance_case_budget_id");

                    b.Property<int?>("TargetCashForWorkBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_cash_for_work_budget_id");

                    b.Property<int?>("TargetProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_program_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("YearlyBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("yearly_budget_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetAssistanceCaseBudgetId");

                    b.HasIndex("TargetCashForWorkBudgetId");

                    b.HasIndex("TargetProgramId");

                    b.ToTable("government_budget_snapshots");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_line");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("head_name");

                    b.Property<string>("HouseholdCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("household_code");

                    b.Property<string>("Purok")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("purok");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdCode")
                        .IsUnique();

                    b.ToTable("households");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.HouseholdMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsCashForWorkEligible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_cash_for_work_eligible");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("occupation");

                    b.Property<string>("RelationshipToHead")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("relationship_to_head");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("household_members");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.PrivateDonation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_received");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("donor_name");

                    b.Property<string>("DonorType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("donor_type");

                    b.Property<string>("ProofFilePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("proof_file_path");

                    b.Property<string>("ProofReferenceNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("proof_reference_number");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("proof_type");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("received_by_user_id");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_number");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("remarks");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetAssistanceCaseBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_assistance_case_budget_id");

                    b.Property<int?>("TargetCashForWorkBudgetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_cash_for_work_budget_id");

                    b.Property<int?>("TargetProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_program_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetAssistanceCaseBudgetId");

                    b.HasIndex("TargetCashForWorkBudgetId");

                    b.HasIndex("TargetProgramId");

                    b.ToTable("private_donations");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.ProjectBudgetSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AyudaProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ayuda_program_id");

                    b.Property<int>("BudgetBucketId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("budget_bucket_id");

                    b.Property<string>("BudgetBucketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("budget_bucket_type");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AyudaProgramId", "Priority");

                    b.ToTable("ayuda_project_budget_sources");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.ScannerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AyudaProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ayuda_program_id");

                    b.Property<int?>("CashForWorkEventId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cash_for_work_event_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_accessed_at");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("LastScannedPayload")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scanned_payload");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("pin_hash");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_token");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("scanner_sessions");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.SyncMetadata", b =>
                {
                    b.Property<string>("TableName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TableName");

                    b.ToTable("sync_metadata");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.SystemRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanySerialNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("company_serial_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastValidatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_validated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanySerialNumber")
                        .IsUnique();

                    b.ToTable("system_registrations");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("CanAccessAppDatabase")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_app_database");

                    b.Property<bool>("CanAccessAssistanceCases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_assistance_cases");

                    b.Property<bool>("CanAccessBorrowing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_borrowing");

                    b.Property<bool>("CanAccessBudget")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_budget");

                    b.Property<bool>("CanAccessCashForWork")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_cash_for_work");

                    b.Property<bool>("CanAccessDashboard")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_dashboard");

                    b.Property<bool>("CanAccessDistribution")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_distribution");

                    b.Property<bool>("CanAccessGgmsBudgetSource")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_ggms_budget_source");

                    b.Property<bool>("CanAccessGgmsTransactions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_ggms_transactions");

                    b.Property<bool>("CanAccessMasterList")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_master_list");

                    b.Property<bool>("CanAccessReports")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_reports");

                    b.Property<bool>("CanAccessScanningPortal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("can_access_scanning_portal");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_permissions");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_path");

                    b.Property<Guid>("SyncId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.ActivityLog", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AssistanceCase", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AssistanceCaseBudget", "AssistanceCaseBudget")
                        .WithMany()
                        .HasForeignKey("AssistanceCaseBudgetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "AyudaProgram")
                        .WithMany()
                        .HasForeignKey("AyudaProgramId");

                    b.HasOne("AttendanceShiftingManagement.Models.BudgetLedgerEntry", "BudgetLedgerEntry")
                        .WithMany()
                        .HasForeignKey("BudgetLedgerEntryId");

                    b.HasOne("AttendanceShiftingManagement.Models.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId");

                    b.HasOne("AttendanceShiftingManagement.Models.HouseholdMember", "HouseholdMember")
                        .WithMany()
                        .HasForeignKey("HouseholdMemberId");

                    b.Navigation("AssistanceCaseBudget");

                    b.Navigation("AyudaProgram");

                    b.Navigation("BudgetLedgerEntry");

                    b.Navigation("Household");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AyudaProgram", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.PrivateDonation", "SourceDonation")
                        .WithMany()
                        .HasForeignKey("SourceDonationId");

                    b.HasOne("AttendanceShiftingManagement.Models.GovernmentBudgetSnapshot", "SourceGGMSBudget")
                        .WithMany()
                        .HasForeignKey("SourceGGMSBudgetId");

                    b.Navigation("SourceDonation");

                    b.Navigation("SourceGGMSBudget");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AyudaProjectBeneficiary", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "AyudaProgram")
                        .WithMany()
                        .HasForeignKey("AyudaProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AyudaProgram");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.AyudaProjectClaim", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "AyudaProgram")
                        .WithMany()
                        .HasForeignKey("AyudaProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AyudaProgram");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.BudgetLedgerEntry", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AssistanceCaseBudget", "AssistanceCaseBudget")
                        .WithMany()
                        .HasForeignKey("AssistanceCaseBudgetId");

                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkBudget", "CashForWorkBudget")
                        .WithMany()
                        .HasForeignKey("CashForWorkBudgetId");

                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.Navigation("AssistanceCaseBudget");

                    b.Navigation("CashForWorkBudget");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkAttendance", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkParticipant", "Participant")
                        .WithMany("Attendances")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceShiftingManagement.Models.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkEvent", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "AyudaProgram")
                        .WithMany()
                        .HasForeignKey("AyudaProgramId");

                    b.HasOne("AttendanceShiftingManagement.Models.BudgetLedgerEntry", "BudgetLedgerEntry")
                        .WithMany()
                        .HasForeignKey("BudgetLedgerEntryId");

                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkBudget", "CashForWorkBudget")
                        .WithMany()
                        .HasForeignKey("CashForWorkBudgetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AttendanceShiftingManagement.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AyudaProgram");

                    b.Navigation("BudgetLedgerEntry");

                    b.Navigation("CashForWorkBudget");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkParticipant", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceShiftingManagement.Models.BeneficiaryStaging", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryStagingId");

                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkEvent", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendanceShiftingManagement.Models.HouseholdMember", "HouseholdMember")
                        .WithMany("CashForWorkParticipants")
                        .HasForeignKey("HouseholdMemberId");

                    b.Navigation("AddedByUser");

                    b.Navigation("Beneficiary");

                    b.Navigation("Event");

                    b.Navigation("HouseholdMember");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.EquipmentBorrowing", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.BarangayAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.GovernmentBudgetSnapshot", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AssistanceCaseBudget", "TargetAssistanceCaseBudget")
                        .WithMany()
                        .HasForeignKey("TargetAssistanceCaseBudgetId");

                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkBudget", "TargetCashForWorkBudget")
                        .WithMany()
                        .HasForeignKey("TargetCashForWorkBudgetId");

                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "TargetProgram")
                        .WithMany()
                        .HasForeignKey("TargetProgramId");

                    b.Navigation("TargetAssistanceCaseBudget");

                    b.Navigation("TargetCashForWorkBudget");

                    b.Navigation("TargetProgram");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.HouseholdMember", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.PrivateDonation", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AssistanceCaseBudget", "TargetAssistanceCaseBudget")
                        .WithMany()
                        .HasForeignKey("TargetAssistanceCaseBudgetId");

                    b.HasOne("AttendanceShiftingManagement.Models.CashForWorkBudget", "TargetCashForWorkBudget")
                        .WithMany()
                        .HasForeignKey("TargetCashForWorkBudgetId");

                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "TargetProgram")
                        .WithMany()
                        .HasForeignKey("TargetProgramId");

                    b.Navigation("TargetAssistanceCaseBudget");

                    b.Navigation("TargetCashForWorkBudget");

                    b.Navigation("TargetProgram");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.ProjectBudgetSource", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.AyudaProgram", "AyudaProgram")
                        .WithMany()
                        .HasForeignKey("AyudaProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AyudaProgram");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.UserPermission", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("AttendanceShiftingManagement.Models.UserPermission", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.UserProfile", b =>
                {
                    b.HasOne("AttendanceShiftingManagement.Models.User", null)
                        .WithOne()
                        .HasForeignKey("AttendanceShiftingManagement.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkEvent", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.CashForWorkParticipant", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.Household", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AttendanceShiftingManagement.Models.HouseholdMember", b =>
                {
                    b.Navigation("CashForWorkParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
